[colors]
background    = "#00AAAA"
foreground    = "#FFFFFF"
cursor_bg     = "#FFFFFF"
cursor_fg     = "#00AAAA"
selection_bg  = "#FFFFFF"
selection_fg  = "#00AAAA"
ansi = ["#00AAAA", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"]
brights = ["#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF", "#FFFFFF"]
