# Get editor-friendly prompts
format = """
[┌───────────────────](bold green)
[│](bold green) $directory$git_branch$git_status
[└─](bold green) $character"""

# Disable modules that cause "Permission denied" or slowness
[package]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true
[aws]
disabled = true

[directory]
style = "bold cyan"
truncate_to_repo = true
truncation_symbol = "…/"

[git_branch]
symbol = "🌱 "
style = "bold green"

[git_status]
style = "bold red"
format = "([\\[$all_status$ahead_behind\\]]($style) )"

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

