theme = "default"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
bufferline = "multiple"
auto-format = true
idle-timeout = 0
true-color = true
gutters = ["diff", "diagnostics", "line-numbers"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace]
render = "all"

[editor.whitespace.characters]
space = " "
newline = " "
tab = "→"      # Виден только TAB
trailing = "·" # Видны только пробелы в конце

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator"]
right = ["position", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
