theme = "default"

[editor]
line-number = "relative"
cursorline = true
scrolloff = 5
scroll-lines = 3
color-modes = true
bufferline = "multiple"
idle-timeout = 0
true-color = true
rulers = [80, 100]
default-yank-register = '+'
auto-format = true
trim-trailing-whitespace = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.whitespace]
render = "all"

# or control each character
# [editor.whitespace.render]
# space = "all"
# tab = "all"
# nbsp = "none"
# nnbsp = "none"
# newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# [editor.statusline]
# left = ["mode", "spacer", "spinner", "spacer", "file-name", "spacer", "file-modification-indicator"]
# right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type"]
# separator = "│"
[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "file-name", "spacer", "file-modification-indicator"]
center = ["version-control"]
right = ["diagnostics", "spacer", "selections", "position", "position-percentage", "spacer", "file-encoding", "file-type"]
separator = "│"

[editor.file-picker]
hidden = false

[keys.normal]
"esc" = ["collapse_selection", "keep_primary_selection"]
