# --- Language Servers Definitions ---
[language-server.nil]
command = "nil"

[language-server.ansible-ls]
command = "ansible-language-server"
args = ["--stdio"]

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]

[language-server.bash-ls]
command = "bash-language-server"
args = ["start"]

# --- Language to Server Mapping ---
[[language]]
name = "nix"
scope = "source.nix"
language-servers = [ "nil" ]

[[language]]
name = "yaml"
scope = "source.yaml"
auto-format = true
language-servers = [ "yaml-language-server" ]

[[language]]
name = "ansible"
scope = "source.ansible"
file-types = ["yaml", "yml"]
roots = ["ansible.cfg", "hosts", "inventory"]
auto-format = true
language-servers = [ "ansible-ls" ]

[[language]]
name = "bash"
scope = "source.bash"
file-types = ["sh", "bash"]
auto-format = true
language-servers = [ "bash-ls" ]
