[language-server.ansible-ls]
command = "ansible-language-server"
args = ["--stdio"]
# Passing path to ansible-lint for local schema validation without internet
config = { ansible = { lint = { enabled = true, path = "ansible-lint" } } }

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]
config = { yaml = { format = { enable = true }, validate = true, schemas = { "kubernetes" = "*.yaml" } } }

[language-server.nil]
command = "nil"

[language-server.bash-ls]
command = "bash-language-server"
args = ["start"]

[[language]]
name = "ansible"
scope = "source.ansible"
file-types = ["yml", "yaml"]
roots = ["ansible.cfg", ".ansible-lint", "roles", "inventory"]
auto-format = true
# Use specialized ansible-ls instead of generic yaml-ls
language-servers = [ { name = "ansible-ls" } ]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yml", "yaml", "json"]
auto-format = true
language-servers = [ { name = "yaml-language-server" } ]

[[language]]
name = "bash"
scope = "source.bash"
file-types = ["sh", "bash"]
auto-format = true
language-servers = [ { name = "bash-ls" } ]
